# Generated by Django 3.1.2 on 2020-11-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0002_movie_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
