# Generated by Django 3.1.2 on 2020-10-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('plate_num', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=8)),
                ('time_1', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
