# Generated by Django 3.1.2 on 2020-10-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='park_area_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slots', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='slot_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('park_area_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.park_area_data')),
            ],
        ),
    ]
