# Generated by Django 3.1.2 on 2020-11-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_park_area_data_slot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='park_area_data',
            name='nu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.person'),
        ),
    ]
